#include "config.h"

const char * LLAMA_COMMIT = "@LLAMA_COMMIT@";
int LLAMA_BUILD_NUMBER = LLAMA_BUILD_NUMBER;
const char * LLAMA_BUILD_TARGET = "@LLAMA_BUILD_TARGET@";
const char * LLAMA_COMPILER = "@LLAMA_COMPILER@";